version: "3.7"
services:
  nginx:
    container_name: bejee_nginx
    image: nginx
    ports:
      - ${APP_PORT:-8083}:80
    volumes:
      - ./.docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker-compose/nignx/logs:/var/log/nginx
      - .:/var/www/html
  php:
    container_name: bejee_php
    build: ./.docker-compose/php
    volumes:
      - .:/var/www/html
      - ./.docker-compose/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: always
    tty: true
    depends_on:
      - mysql

  mysql:
    container_name: bejee_mysql
    image: mysql:8.0
    volumes:
      - ./.docker-compose/mysql/dump.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.docker-compose/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${FORWARD_DB_PORT:-3306}:3306
    restart: always
