version: "3.7"

services:
  nginx:
    container_name: bejee_nginx
    image: nginx
    ports:
      - 8080:80
    volumes:
    - ./.docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./.docker-compose/nignx/logs:/var/log/nginx
    - .:/var/www/html
  php:
    container_name: bejee_php
    build: ./.docker-compose/php
    volumes:
    - .:/app
    - ./.docker-compose/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: always
    tty: true

  postgres:
    container_name: bejee_postgres
    image: postgres:12.4
    volumes:
      - "./.docker-compose/postgres/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    restart: always
